config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, :controllers => {
    :registrations => 'admin_users/registrations',
    :sessions => 'admin_users/sessions'
  }

  root to: 'articles#index'
  resources :articles, only: [:index, :show]
  resources :tags, param: :name, only: :show, :constraints => { :name => /[^\/]*/ }
  get 'admin' => 'admin/base#index'
  get 'admin/manager/articles' => 'admin/manager#articles'
  get 'admin/manager/rankings' => 'admin/manager#rankings'
  get 'admin/manager/admin_users' => 'admin/manager#admin_users'
  post 'admin/manager/change_authority' => 'admin/manager#change_authority'

  namespace :admin do
    resources :articles do
      collection do
        post 'preview'
      end
    end
    resources :tags
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :admin_user
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :footprints

  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true
  validates :main_image_url, presence: true, length: { maximum: 200 }

  class << self
    def sort_by_footprints
      joins(:footprints).group(:article_id).order('SUM(articles.id) DESC')
    end

    def published
      where(is_draft: false, is_public: true)
    end

    def draft
      where(is_draft: true)
    end

    def closed
      where(is_public: false)
    end

    def yesterday
      where("articles.created_at >= ?", Date.yesterday.beginning_of_day).where('articles.created_at < ?', Date.today.beginning_of_day)
    end

    def each_day_counts_list(user_id=nil)
      start_date = Date.new(2015, 01, 07)
      end_date = Date.new(2015, 01, 31)
      day_range = start_date..end_date
      [].tap do |ary|
        day_range.each do |day|
          ary << [day, where(admin_user_id: user_id).where('created_at >= ?', day.beginning_of_day).where('created_at < ?', day.tomorrow.beginning_of_day).count.to_i]
        end
      end
    end

    def all_each_day_counts_list
      start_date = Date.new(2015, 01, 07)
      end_date = Date.new(2015, 01, 31)
      day_range = start_date..end_date
      [].tap do |ary|
        day_range.each do |day|
          ary << [day, where('created_at >= ?', day.beginning_of_day).where('created_at < ?', day.tomorrow.beginning_of_day).count.to_i]
        end
      end
    end

    def each_user_articles_count_list
      start_date = Date.new(2015, 01, 07)
      end_date = Date.new(2015, 01, 31)
      ary = []
      AdminUser.all.each do |user|
        if user.manager? || user.member?
          ary << [user.name, published.where(admin_user_id: user.id).where('created_at >=?', start_date).where('created_at < ?', end_date).count]
        end
      end
      ary.sort { |a,b|
        a[1] <=> b[1]
      }
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :manager, only: :destroy
  before_filter :disable_xss_protection
  include MarkdownHelper

  def index
    @published_articles = current_admin_user.articles.published.order('created_at DESC').page(params[:page]).per(10)
    @draft_articles = current_admin_user.articles.draft.order('created_at DESC').page(params[:page]).per(10)
    @closed_articles = current_admin_user.articles.closed.order('created_at DESC').page(params[:page]).per(10)
  end

  def show
  end

  def new
    @article = Article.new()
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.admin_user = current_admin_user

    if @article.save
      redirect_to admin_path, notice: 'お疲れ様です！記事が作成されました :)'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to admin_article_path(@article), notice: 'お疲れ様です！無事に更新されました！ :D'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_manager_articles_path, notice: "「#{@article.title}」の記事を削除しました。"
  end

  def preview
    render text: markdown(params[:text])
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    @post_params ||= begin
      param_hash = params.require(:article).permit(:title, :description, :content, :tags, :main_image_url, :is_draft, :is_public).to_hash

      # tags_text == 'Javascript,Ruby'
      tags_text = param_hash.delete('tags')

      tags = tags_text.split(',').map do |tag_name|
        Tag.find_or_create_by(name: tag_name)
      end
      param_hash['tag_ids'] = tags.map(&:id)

      param_hash
    end
  end
protected
  def disable_xss_protection
    # Disabling this is probably not a good idea,
    # but the header causes Chrome to choke when being
    # redirected back after a submit and the page contains an iframe.
    response.headers['X-XSS-Protection'] = "0"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.published.order('updated_at DESC').page(params[:page]).per(10)
    @latests = Article.published.order('articles.created_at DESC').limit(5)
    @rankings = Article.published.yesterday.sort_by_footprints.limit(5)
  end

  # GET /articles/1
  def show
    redirect_to articles_path if @article.is_draft?
    Footprint.visit!(@article)
    @rankings = Article.published.yesterday.sort_by_footprints.limit(5)
    @latests = Article.published.order('created_at DESC').limit(5)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'お疲れ様です！記事が作成されました :)'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'お疲れ様です！無事に更新されました！ :D'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: '記事を削除しました ;('
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :description, :content, :main_image_url, :is_draft)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/_form.html.slim
.row
  .col.s12.l12#write-article-wrapper
    = form_for(@article, url: url, method: method) do |f|
      - if @article.errors.any?
        #error_explanation
          h2 = "#{pluralize(@article.errors.count, "")} つのエラーがあります。"
          ol
            - @article.errors.full_messages.each do |message|
              li = message

      .field
        = f.label :title
        label.required 必須
        label.counter-label.first-label ※現在
        label.counter.js-title-counter -
        label.counter-label 文字（文字数の目安:30〜40文字）
        = f.text_field :title, placeholder: '例）【海外でも大人気】BABY METAL（ベビーメタル）のおすすめ人気曲まとめ'
      .field
        = f.label :description
        label.required 必須
        label.counter-label.first-label ※現在
        label.counter.js-desc-counter -
        label.counter-label 文字（文字数の目安:120〜130文字）
        = f.text_area :description
      .field.rich-textarea
        = f.label :content
        label.required 必須
        label.counter-label.first-label 文字数の目安:1,500〜2,000文字
        br
        label.required-label 画像を使うときは画像URLを貼って下さい。アップロードはできません。また、Heading1は使用不可です。
        = f.text_area :content , class: 'textarea-lg'
      .field
        = f.label :main_image_url
        label.required 必須
        label.counter-label.first-label ※一覧ページ及びシェアの時に表示されます。
        = f.text_field :main_image_url, placeholder: '例）http://www.freebit.com/images/goosehouse.jpg'
      .field
        = f.label :tags
        label.counter-label.first-label ※複数の場合は「, 」で区切る（半角のコンマ。スペースなし）
        = text_field :article, :tags, value: @article.tags.map{ |_tag| _tag.name }.join(','), placeholder: '例) バンド,今話題,Goose House'
      .field
        = f.check_box :is_draft
        = f.label :is_draft, '下書きとして保存'
      - if current_admin_user.manager? && params[:action] == 'edit'
        .field
          = f.check_box :is_public
          = f.label :is_public, '公開'
      br
      .actions = f.submit '保存する', class: 'btn waves-effect waves-light'

  .col.s12.l8#preview-wrapper
    .page-header
      p
        i.mdi-editor-border-color
        | プレビュー
    p.btn.waves-effect.waves-light#js-reload-preview 更新
    = render 'shared/preloader'
    .article-show-wrapper
      .article-show-main-header
        h1.article-title#title-preview
        p.article-desc#desc-preview
      .markdown
        #content-preview

= javascript_include_tag 'main/articles'
= javascript_include_tag 'main/richtext'
= javascript_include_tag 'main/text_counter'
= javascript_include_tag 'main/text_preview'

javascript:
  $('.modal-trigger').leanModal();

app/views/admin/articles/_writing_style_modal.html.slim
#writing-style-modal.modal
  h4 記事の書き方
  p 記事はマークダウン記法という書き方で書きます。

  h5 1. 見出しの書き方
  p 見出しを書くときには、#をつけます。
  p.example （書き方の例）
  p # 見出しです。
  p.example （表示のされ方）
  .markdown
    p = markdown("# 見出しです。")

  p また##と書くと、小見出しになります。
  p.example （書き方の例）
  p ## 小見出しです。
  p.example （表示のされ方）
  .markdown
    p = markdown("## 小見出しです。")

  h5 2. 画像の挿入方法
  p 画像を入れるときには、下記のように書きます。また、引用元も記載してください。（アスタリスクで囲む）
  p.example （書き方の例）
  p ![画像の説明テキスト](画像URL)
  p
    | *引用元:Flickr*
  p.example （表示のされ方）
  .markdown
    p = markdown("![Goose House](http://www.freebit.com/press/images/201311/20131113_fbm_goosehouse_02.jpg)")
    p = markdown("*引用元:Flickr*")

  h5 3. Youtube動画の埋め込み方法
  p Youtube動画を埋め込むときには、Youtubeの動画ページの動画の下にある「共有」→「埋め込みコード」を選択し、コードをコピーしてから、貼り付けて下さい。また、埋め込みコードを貼り付けたあと、埋め込みコードの次の行に、引用元を書いて下さい。
  p "<iframe width="560" height="315" src="//www.youtube.com/embed/ONNFHTOueXo" frameborder="0" allowfullscreen></iframe>"
  p = markdown("*引用元:Youtube*")

  h5 4. テキストの引用をする方法
  p テキストを引用する場合は、下記のように書いて下さい。
  p.example （書き方の例）
  p > 引用文がここに入ります。
  p > 引用文がここに入ります。
  p > *引用元をここに書きます*
  p.example （表示のされ方）
  .markdown
    p = markdown("> 引用文がここに入ります。<br>引用文がここに入ります。<br> *引用元をここに書きます*")

app/views/admin/articles/edit.html.slim
== render partial: 'form', locals: {method: :put, url: admin_article_path}

= link_to 'Back', admin_articles_path

app/views/admin/articles/index.html.slim
.col.s12
  ul.tabs
    li.tab.col.s2.l6
      a href='#published' 公開済み (#{@published_articles.total_count}件)
    li.tab.col.s2.l6
      a href='#draft' 下書き (#{@draft_articles.total_count}件)
#published
  table.striped
    thead
      tr
        th 日付
        th タイトル
        th 獲得PV
        th
    tbody
      - @published_articles.each do |article|
        tr
          td = time_display(article.created_at)
          td = link_to(article.title, admin_article_path(article))
          td = article.footprints.count
          td = link_to '編集', edit_admin_article_path(article)
  = paginate @published_articles, window: 1
#draft
  table.striped
    thead
      tr
        th 日付
        th タイトル
        th 獲得PV
        th
    tbody
      - @draft_articles.each do |article|
        tr
          td = time_display(article.created_at)
          td = link_to(article.title, admin_article_path(article))
          td = article.footprints.count
          td = link_to '編集', edit_admin_article_path(article)
  = paginate @draft_articles, window: 1
javascript:
 $('ul.tabs').tabs();
 $.materialize.init();

app/views/admin/articles/new.html.slim
== render partial: 'form', locals: {method: :post, url: admin_articles_path}

app/views/admin/articles/show.html.slim
.row.article-show-wrapper
  .col.s12.l8.main-col
    .article-show-sub-header
      p.article-date
        = time_display(@article.created_at)
        | 更新
      p
        = link_to '本サイトで記事を見る', article_path(@article)
    .article-show-main-header
      h1.article-title = @article.title
      p.article-desc = @article.description
    .article-show-content.markdown
      p = markdown(@article.content)
= link_to '編集する', edit_admin_article_path(@article), class: 'btn waves-effect waves-light'
= javascript_include_tag 'main/articles'