config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, :controllers => {
    :registrations => 'admin_users/registrations',
    :sessions => 'admin_users/sessions'
  }

  root to: 'articles#index'
  resources :articles, only: [:index, :show]
  resources :tags, param: :name, only: :show, :constraints => { :name => /[^\/]*/ }
  get 'admin' => 'admin/base#index'
  get 'admin/manager/articles' => 'admin/manager#articles'
  get 'admin/manager/rankings' => 'admin/manager#rankings'
  get 'admin/manager/admin_users' => 'admin/manager#admin_users'
  post 'admin/manager/change_authority' => 'admin/manager#change_authority'

  namespace :admin do
    resources :articles do
      collection do
        post 'preview'
      end
    end
    resources :tags
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :admin_user
  has_many :article_tags
  has_many :tags, through: :article_tags
  has_many :footprints

  validates :title, presence: true
  validates :description, presence: true
  validates :content, presence: true
  validates :main_image_url, presence: true, length: { maximum: 200 }

  class << self
    def sort_by_footprints
      joins(:footprints).group(:article_id).order('SUM(articles.id) DESC')
    end

    def published
      where(is_draft: false, is_public: true)
    end

    def draft
      where(is_draft: true)
    end

    def closed
      where(is_public: false)
    end

    def yesterday
      where("articles.created_at >= ?", Date.yesterday.beginning_of_day).where('articles.created_at < ?', Date.today.beginning_of_day)
    end

    def each_day_counts_list(user_id=nil)
      start_date = Date.new(2015, 01, 07)
      end_date = Date.new(2015, 01, 31)
      day_range = start_date..end_date
      [].tap do |ary|
        day_range.each do |day|
          ary << [day, where(admin_user_id: user_id).where('created_at >= ?', day.beginning_of_day).where('created_at < ?', day.tomorrow.beginning_of_day).count.to_i]
        end
      end
    end

    def all_each_day_counts_list
      start_date = Date.new(2015, 01, 07)
      end_date = Date.new(2015, 01, 31)
      day_range = start_date..end_date
      [].tap do |ary|
        day_range.each do |day|
          ary << [day, where('created_at >= ?', day.beginning_of_day).where('created_at < ?', day.tomorrow.beginning_of_day).count.to_i]
        end
      end
    end

    def each_user_articles_count_list
      start_date = Date.new(2015, 01, 07)
      end_date = Date.new(2015, 01, 31)
      ary = []
      AdminUser.all.each do |user|
        if user.manager? || user.member?
          ary << [user.name, published.where(admin_user_id: user.id).where('created_at >=?', start_date).where('created_at < ?', end_date).count]
        end
      end
      ary.sort { |a,b|
        a[1] <=> b[1]
      }
    end
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_filter :manager, only: :destroy
  before_filter :disable_xss_protection
  include MarkdownHelper

  def index
    @published_articles = current_admin_user.articles.published.order('created_at DESC').page(params[:page]).per(10)
    @draft_articles = current_admin_user.articles.draft.order('created_at DESC').page(params[:page]).per(10)
    @closed_articles = current_admin_user.articles.closed.order('created_at DESC').page(params[:page]).per(10)
  end

  def show
  end

  def new
    @article = Article.new()
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.admin_user = current_admin_user

    if @article.save
      redirect_to admin_path, notice: 'お疲れ様です！記事が作成されました :)'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to admin_article_path(@article), notice: 'お疲れ様です！無事に更新されました！ :D'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to admin_manager_articles_path, notice: "「#{@article.title}」の記事を削除しました。"
  end

  def preview
    render text: markdown(params[:text])
  end

private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    @post_params ||= begin
      param_hash = params.require(:article).permit(:title, :description, :content, :tags, :main_image_url, :is_draft, :is_public).to_hash

      # tags_text == 'Javascript,Ruby'
      tags_text = param_hash.delete('tags')

      tags = tags_text.split(',').map do |tag_name|
        Tag.find_or_create_by(name: tag_name)
      end
      param_hash['tag_ids'] = tags.map(&:id)

      param_hash
    end
  end
protected
  def disable_xss_protection
    # Disabling this is probably not a good idea,
    # but the header causes Chrome to choke when being
    # redirected back after a submit and the page contains an iframe.
    response.headers['X-XSS-Protection'] = "0"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.published.order('updated_at DESC').page(params[:page]).per(10)
    @latests = Article.published.order('articles.created_at DESC').limit(5)
    @rankings = Article.published.yesterday.sort_by_footprints.limit(5)
  end

  # GET /articles/1
  def show
    redirect_to articles_path if @article.is_draft?
    Footprint.visit!(@article)
    @rankings = Article.published.yesterday.sort_by_footprints.limit(5)
    @latests = Article.published.order('created_at DESC').limit(5)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'お疲れ様です！記事が作成されました :)'
    else
      render :new
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'お疲れ様です！無事に更新されました！ :D'
    else
      render :edit
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: '記事を削除しました ;('
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def article_params
      params.require(:article).permit(:title, :description, :content, :main_image_url, :is_draft)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_side_col.html.slim
= render 'adsense/column_top'
- if @rankings.present?
  .title-section
    p
      i.mdi-action-trending-up
      | アクセスランキング
    small 昨日人気のあったまとめ
- @rankings.each do |ranking|
  .article-list-wrapper.side-list-wrapper
    .card
      .col.s4.l4
        .thumbnail.thumbnail-small style="background-image: url('#{ranking.main_image_url}');"
      .col.s8.l8
        - if ranking.tags.map {|_tag| _tag.name }.include?('動画')
          p.article-title
            a rel='nofollow' href=article_path(ranking) #{ranking.title}
        - else
          p.article-title = link_to(ranking.title, article_path(ranking))
        p.article-desc = truncate(ranking.description, length: 30)
= render 'adsense/column_middle'
.title-section
  p
    i.mdi-image-audiotrack
    | 新着のまとめ
  small 新着トレンドをゲットしよう
- @latests.each do |latest|
  .article-list-wrapper.side-list-wrapper
    .card
      .col.s4.l4
        .thumbnail.thumbnail-small style="background-image: url('#{latest.main_image_url}');"
      .col.s8.l8
        - if latest.tags.map {|_tag| _tag.name }.include?('動画')
          p.article-title
            a rel='nofollow' href=article_path(latest) #{latest.title}
        - else
          p.article-title = link_to(latest.title, article_path(latest))
        p.article-desc = truncate(latest.description, length: 40)
= render 'adsense/column_bottom'

app/views/articles/index.html.slim
.row
  section.col.s12.l8.main-col
    - @articles.each do |article|
      article.row.article-list-wrapper
        .card
          .col.s4.l2
            .thumbnail style="background-image: url('#{article.main_image_url}');"
          .col.s8.l10
            - if article.tags.map {|_tag| _tag.name }.include?('動画')
              p.article-title
                a rel='nofollow' href=article_path(article) #{article.title}
            - else
              p.article-title = link_to(article.title, article_path(article))
            p.article-desc = truncate(article.description, length: 82)
            span.article-writer = article.admin_user.try(:nickname)
            span.split-separator |
            span.article-footprints
              = article.footprints.count
              |  view
    - if request.user_agent =~ /Android|iPhone/
      = paginate @articles, window: 0
    - else
      = paginate @articles, window: 1
  aside.col.s12.l4.side-col
    = render 'side_col'

app/views/articles/show.html.slim
.row.article-show-wrapper
  article.col.s12.l8.main-col
    .article-show-sub-header
      p.article-date
        = time_display(@article.created_at)
        | 更新
      - if request.user_agent =~ /Android|iPhone/
        br
      - @article.tags.limit(3).each do |tag|
        = link_to "#{tag.name}(#{tag.articles_count})", tag_path(tag.name), class: 'article-tags'
    .article-show-main-header
      h1.article-title = @article.title
      p.article-desc = @article.description
      = render 'shared/social'
      p.footprints
        = @article.footprints.count
        small views
      br
      = render 'adsense/article_top'
      br
      - if current_admin_user && current_admin_user.manager? || current_admin_user && current_admin_user.member?
        .card.blue-grey.darken-1.admin-info-card
          .card-content.white-text
            span.card-title 記事情報
            p ライター: #{@article.admin_user.name}
            p 最終更新日: #{time_display(@article.updated_at)}
          .card-action
            = link_to '編集する', edit_admin_article_path(@article)
    .article-show-content.markdown
      p = markdown(@article.content)
    = render 'adsense/article_bottom'
    .article-show-footer
      = render 'shared/social'
      br
      .facebook-likebox-wrapper
        p いいね！を押して人気・話題の音楽情報を受け取ろう
        = render 'shared/facebook'
  aside.col.s12.l4.side-col
    = render 'side_col'
#js-goto-top.btn-floating.waves-effect.waves-light
  i.mdi-hardware-keyboard-arrow-up
= render 'adsense/window_fixed_bottom'

= javascript_include_tag 'main/articles'
= javascript_include_tag 'main/scroll'