config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, :controllers => {
    :registrations => 'admin_users/registrations',
    :sessions => 'admin_users/sessions'
  }

  root to: 'articles#index'
  resources :articles, only: [:index, :show]
  resources :tags, param: :name, only: :show, :constraints => { :name => /[^\/]*/ }
  get 'admin' => 'admin/base#index'
  get 'admin/manager/articles' => 'admin/manager#articles'
  get 'admin/manager/rankings' => 'admin/manager#rankings'
  get 'admin/manager/admin_users' => 'admin/manager#admin_users'
  post 'admin/manager/change_authority' => 'admin/manager#change_authority'

  namespace :admin do
    resources :articles do
      collection do
        post 'preview'
      end
    end
    resources :tags
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :article_tags
  has_many :articles, through: :article_tags
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      redirect_to admin_tag_path(@tag), notice: 'Tag was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tags/1
  def update
    if @tag.update(tag_params)
      redirect_to admin_tag_path(@tag), notice: 'Tag was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    redirect_to admin_tags_path, notice: 'Tag was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def tag_params
      params.require(:tag).permit(:name, :body, :ancestry)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: :show

  def show
    @articles = @tag.articles.published.page(params[:page]).per(10)
    @latests = Article.published.order('articles.created_at DESC').limit(5)
    @rankings = Article.published.yesterday.sort_by_footprints.limit(5)
  end

private
  def set_tag
    @tag = Tag.find_by(name: params[:name]) or fail ActiveRecord::RecordNotFound
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_form.html.slim
= form_for(@tag, url: url, method: method) do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, "error")} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :ancestry
    = f.text_field :ancestry
  .actions = f.submit 'Save'

app/views/admin/tags/edit.html.slim
h1 Editing tag

== render partial: 'form', locals: {method: :put, url: admin_tag_path}

= link_to 'Back', admin_tags_path

app/views/admin/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th name
      th body
      th ancestry
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.name
        td = tag.body
        td = tag.ancestry
        td = link_to 'Show', admin_tag_path(tag)
        td = link_to 'Edit', edit_admin_tag_path(tag)
        td = link_to 'Destroy', admin_tag_path(tag), data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Tag', new_admin_tag_path

app/views/admin/tags/new.html.slim
h1 New tag

== render partial: 'form', locals: {method: :post, url: admin_tags_path}

app/views/admin/tags/show.html.slim
p#notice = notice

p
  strong Title:
  = @tag.name
p
  strong Description:
  = @tag.body
p
  strong Content:
  = @tag.ancestry

= link_to 'Edit', edit_admin_tag_path(@tag)
'|
= link_to 'Back', admin_tags_path