config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, :controllers => {
    :registrations => 'admin_users/registrations',
    :sessions => 'admin_users/sessions'
  }

  root to: 'articles#index'
  resources :articles, only: [:index, :show]
  resources :tags, param: :name, only: :show, :constraints => { :name => /[^\/]*/ }
  get 'admin' => 'admin/base#index'
  get 'admin/manager/articles' => 'admin/manager#articles'
  get 'admin/manager/rankings' => 'admin/manager#rankings'
  get 'admin/manager/admin_users' => 'admin/manager#admin_users'
  post 'admin/manager/change_authority' => 'admin/manager#change_authority'

  namespace :admin do
    resources :articles do
      collection do
        post 'preview'
      end
    end
    resources :tags
  end
end

app/controllers/admin/manager_controller.rb
class Admin::ManagerController < Admin::BaseController
  before_filter :manager, only: [:change_authority]
  def articles
    @search = Article.published.order('created_at DESC').search(params[:q])
    @published_articles = @search.result.page(params[:page]).per(25)
    @draft_articles = Article.draft.order('created_at DESC').page(params[:page]).per(25)
    @closed_articles = Article.closed.order('created_at DESC').page(params[:page]).per(25)
  end

  def rankings
    gon.articles = Article.published.all_each_day_counts_list
    gon.each_user_articles_count = Article.published.each_user_articles_count_list
    gon.each_user_footprints_count = AdminUser.each_user_footprints_count_list
  end

  def admin_users
    @admin_users = AdminUser.all.order('created_at DESC')
  end

  def change_authority
    @admin_user = AdminUser.find_by_id(params[:admin_user_id])

    @admin_users = AdminUser.all.order('created_at DESC')
    if @admin_user != nil
      @admin_user.update(role: params[:value].to_i)

      html = render_to_string partial: 'admin/manager/admin_users_list', collection: [@admin_users]
      flash.now[:notice] = '更新されました。'
      render json: { html: html }
    else
      flash.now[:notice] = 'エラーが発生ました。'
      render json: { error: false }, status: 400
    end

  end
end

app/views/admin/manager/_admin_users_list.html.slim
table.striped
  thead
    tr
      th 氏名
      th ニックネーム
      th アドレス
      th 属性
      th 作成記事数
      th 合計獲得PV
      th 属性
  tbody
    - @admin_users.each do |user|
      tr
        td = user.name || '未設定'
        td = user.nickname || '未設定'
        td = user.email
        td = user.role
        td = user.articles.published.count
        td = user.footprints_count
        - if current_admin_user.manager?
          td = select_tag :admin_user_role, options_for_select(AdminUser.roles, user[:role]), {class: 'js-change-role', data: { id: user[:id] }}
        - else
          td = user.role
= javascript_include_tag 'admin/admin_users'

app/views/admin/manager/admin_users.html.slim
.row
  #admin_users_list
    = render partial: 'admin_users_list', locals: {admin_users: @admin_users}

app/views/admin/manager/articles.html.slim
.col.s12
  ul.tabs
    li.tab.col.s2.l6
      a href='#published' 公開済み (#{@published_articles.total_count}件)
    li.tab.col.s2.l6
      a href='#draft' 下書き (#{@draft_articles.total_count}件)
    li.tab.col.s2.l6
      a href='#closed' 非公開 (#{@closed_articles.total_count}件)
#published
  blockquote
    h5 検索フォーム
    = search_form_for @search, url: admin_manager_articles_path do |f|
      .field
        = f.label :title, '記事のタイトル'
        = f.text_field :title_cont
      = f.submit '検索する', class: 'btn waves-effect waves-light'
  table.striped
    thead
      tr
        th 日付
        th タイトル
        th Writer
        th 獲得PV
        - if current_admin_user.manager?
          th
          th
    tbody
      - @published_articles.each do |article|
        tr
          td = time_display(article.created_at)
          td = link_to(article.title, admin_article_path(article))
          td = article.admin_user.try(:name)
          td = article.footprints.count
          - if current_admin_user.manager?
            td = link_to '編集', edit_admin_article_path(article)
            td = link_to '削除', admin_article_path(article), method: :delete, data: { confirm: '本当に消していいですか？' }
  = paginate @published_articles, window: 1
#draft
  table.striped
    thead
      tr
        th 日付
        th タイトル
        th Writer
        th 獲得PV
        th
        th
    tbody
      - @draft_articles.each do |article|
        tr
          td = time_display(article.created_at)
          td = link_to(article.title, admin_article_path(article))
          td = article.admin_user.try(:name)
          td = article.footprints.count
          td = link_to '編集', edit_admin_article_path(article)
          td = link_to '削除', admin_article_path(article), method: :delete, data: { confirm: '本当に消していいですか？' }
  = paginate @draft_articles, window: 1
#closed
  table.striped
    thead
      tr
        th 日付
        th タイトル
        th Writer
        th 獲得PV
        th
        th
    tbody
      - @closed_articles.each do |article|
        tr
          td = time_display(article.created_at)
          td = link_to(article.title, admin_article_path(article))
          td = article.admin_user.try(:name)
          td = article.footprints.count
          td = link_to '編集', edit_admin_article_path(article)
          td = link_to '削除', admin_article_path(article), method: :delete, data: { confirm: '本当に消していいですか？' }
  = paginate @published_articles, window: 1
javascript:
 $('ul.tabs').tabs();
 $.materialize.init();

app/views/admin/manager/rankings.html.slim
#rankings
  h5
    i.mdi-action-assessment
    | Brand Name全体の記事数推移
  canvas#canvas height="350" width="800"
  h5
    i.mdi-action-trending-up
    | 記事数ランキング
  canvas#articles_count_ranking height="350" width="800"
  h5
    i.mdi-action-trending-up
    | 獲得PVランキング
  canvas#footprints_count_ranking height="350" width="800"

= javascript_include_tag 'admin/chart'